Repository MattJeanes/TARDIS, pull requests merged in 2021-03, with the labels that each got.

#389 Isomorphic Bypassing
  lua/entities/gmod_tardis_interior/modules/sh_security.lua
  lua/tardis/parts/door.lua
Labels: feature

#386 Interior tips
  lua/entities/gmod_tardis_interior/modules/cl_tips.lua
  lua/tardis/interiors/base.lua
  lua/tardis/interiors/legacy.lua
  lua/tardis/sh_menuoptions.lua
Labels: feature, feature parity

#388 Screen button tip [AFTER Screen Improvements and Interior Tips]
  lua/tardis/interiors/legacy.lua
Labels: feature, needs info

#387 Screen improvements
  lua/entities/gmod_tardis/modules/sh_flight.lua
  lua/entities/gmod_tardis/modules/sh_float.lua
  lua/entities/gmod_tardis/modules/sh_health.lua
  lua/entities/gmod_tardis/modules/sh_physlock.lua
  lua/entities/gmod_tardis/modules/sh_power.lua
  lua/entities/gmod_tardis/modules/sh_teleport.lua
  lua/entities/gmod_tardis_interior/modules/cl_lights.lua
  lua/entities/gmod_tardis_interior/modules/sh_power.lua
  lua/entities/gmod_tardis_interior/modules/sh_screens.lua
  lua/tardis/interiors/base.lua
  lua/tardis/interiors/legacy.lua
  lua/tardis/parts/legacy/legacy_screenbutton.lua
  lua/tardis/screens/cl_visualgui_settings.lua
  lua/tardis/screens/sh_screenbutton.lua
  lua/tardis/screens/sh_virtualconsole.lua
  lua/tardis/sh_menuoptions.lua
  lua/tardis/sh_screens.lua
  materials/vgui/tardis-desktop-themes/default/off/interior_screens.png
  materials/vgui/tardis-desktop-themes/default/on/interior_screens.png
Labels: enhancement, feature, feature parity

#390 Tip styles a player can choose
  lua/entities/gmod_tardis_interior/modules/cl_tips.lua
  lua/tardis/interiors/base.lua
  lua/tardis/sh_menuoptions.lua
  lua/tardis/sh_tip_styles.lua
  lua/tardis/themes/tips/classic.lua
  lua/tardis/themes/tips/default.lua
  lua/tardis/themes/tips/white_on_blue.lua
  lua/tardis/themes/tips/white_on_grey.lua
Labels: enhancement, feature

#430 Fix #424 (Damage in vortex)
  lua/entities/gmod_tardis/modules/sh_health.lua
  lua/entities/gmod_tardis/modules/sh_teleport.lua
Labels: type: bug

#469 Organised options by logical categories
  lua/entities/gmod_tardis/modules/cl_projectedlight.lua
  lua/entities/gmod_tardis/modules/sh_doors.lua
  lua/entities/gmod_tardis/modules/sh_flight.lua
  lua/entities/gmod_tardis/modules/sh_light.lua
  lua/entities/gmod_tardis/modules/sh_lock.lua
  lua/entities/gmod_tardis/modules/sh_teleport.lua
  lua/entities/gmod_tardis/modules/sh_vortex.lua
  lua/entities/gmod_tardis_interior/modules/cl_flight.lua
  lua/entities/gmod_tardis_interior/modules/cl_idlesound.lua
  lua/entities/gmod_tardis_interior/modules/cl_render.lua
  lua/entities/gmod_tardis_interior/modules/sh_cloisterbells.lua
  lua/entities/gmod_tardis_interior/modules/sh_portals.lua
  lua/entities/gmod_tardis_interior/modules/sh_security.lua
  lua/tardis/cl_sound.lua
  lua/tardis/screens/cl_visualgui_settings.lua
Labels: type: (3) - cleanup
